### ISSUE TITLE
Suggested Readme Adds

### ISSUE THREAD

**Issue by spwilson2** [daxpedda/unchecked_unwrap#13]
1. As noted by the readme, this crate is basically the same purpose as https://crates.io/crates/unsafe_unwrap, but this crate offers quite a few other features. It'd be helpful to list the additional features within the alternatives section. (Or in a new section.)

2. unsafe_unwrap also posts number for unwrap() vs unsafe_unwrap(), it'd be helpful to add these to the readme for unchecked_unwrap to show that they are basically equivalent for the additional features here.

3. In the docs it might be worth adding example generated assembly for both versions of unwrap.

**Comment by daxpedda** [comment]
Fixed in #14.

**Comment by daxpedda** [comment]
@spwilson2 thank you for taking a look btw!
